local set = vim.api.nvim_set_var

set('loaded_2html_plugin', 1)
set('loaded_cfilter', 1)
set('loaded_gzip', 1)
set('loaded_man', 1)
set('loaded_matchit', 1)
set('loaded_matchparen', 1)
set('loaded_msgpack_autoload', 1)
set('loaded_netrw', 1)
set('loaded_netrwFileHandlers', 1)
set('loaded_netrwPlugin', 1)
set('loaded_netrwSettings', 1)
set('loaded_remote_plugins', 1)
set('loaded_shada_autoload', 1)
set('loaded_shada_plugin', 1)
set('loaded_spellfile_plugin', 1)
set('loaded_sql_completion', 1)
set('loaded_syntax_completion', 1)
set('loaded_tar', 1)
set('loaded_tarPlugin', 1)
set('loaded_tutor_mode_plugin', 1)
set('loaded_vimball', 1)
set('loaded_vimballPlugin', 1)
set('loaded_zip', 1)
set('loaded_zipPlugin', 1)

set('loaded_python3_provider', 0)
set('loaded_node_provider', 0)
set('loaded_ruby_provider', 0)
set('loaded_perl_provider', 0)

set('did_install_default_menus', 1)
set('did_install_syntax_menu', 1)
